api:
  base_url: "https://jsonplaceholder.typicode.com"
  timeout: 30
  verify_ssl: true
  cert_path: null
  mock: false

auth:
  token_expire: 1800
  refresh_threshold: 300

database:
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: "root"
    database: "test_db"
    pool_size: 5
    timeout: 30

# 测试环境特定配置
logging:
  level: DEBUG
  file_level: DEBUG
  console_level: DEBUG

# 其他测试环境特定的配置项