# 通用配置
env: dev  # 默认使用dev环境

logging:
  level: DEBUG
  file_level: DEBUG
  console_level: INFO
  format: "[%(asctime)s] %(levelname)s [%(filename)s:%(lineno)d] - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

# 环境特定配置将从 env/ 目录下加载